f = open('C:/Users/arbag/Desktop/файлы python/20.txt')
f = f.readline()
s = []
s.append(f.count('AA'))
s.append(f.count('AB'))
s.append(f.count('AC'))
s.append(f.count('AD'))
s.append(f.count('AE'))
s.append(f.count('AF'))
s.append(f.count('AG'))
s.append(f.count('AH'))
s.append(f.count('AI'))
s.append(f.count('AJ'))
s.append(f.count('AK'))
s.append(f.count('AL'))
s.append(f.count('AM'))
s.append(f.count('AN'))
s.append(f.count('AO'))
s.append(f.count('AP'))
s.append(f.count('AQ'))
s.append(f.count('AR'))
s.append(f.count('AS'))
s.append(f.count('AT'))
s.append(f.count('AU'))
s.append(f.count('AV'))
s.append(f.count('AW'))
s.append(f.count('AX'))
s.append(f.count('AY'))
s.append(f.count('AZ'))
print(max(s),s)
print(f.count('AG'))